### ISSUE TITLE
end2end-sci-pdf-parsing doesn't work

### ISSUE THREAD

**Issue by dennissoftman** [allenai/vila#31] opened 2022-10-06 13:35 UTC
Running example code, following README line by line produces this error:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/42491173/194327132-f4972b60-b483-4a7f-8a26-27444c3ff694.png">

any ideas on how to fix that?

**Comment by lolipopshock** [comment] 2022-10-17 03:45
Thank you @dennissoftman for reporting this issue ! And may I ask a bit more details to better help me identify this issue -- 
1. Is it the direct output of the used docker container? 
2. Does it only happen to one specific paper, or for every paper you've passed in? 
    - If it is the former case, any chance you can provide a link/URL to the original paper so I can check what's going on?

**Comment by dennissoftman** [comment] 2022-10-17 12:07
1. Yes, this is output from docker, that's what I've seen in terminal after uploading document 
2. I've used this document from example: "https://arxiv.org/pdf/2106.00676.pdf"
So basically I was just following step-by-step this example https://github.com/allenai/vila/tree/main/examples/end2end-sci-pdf-parsing

**Comment by lolipopshock** [comment] 2022-10-17 16:08
Thank you very much @dennissoftman ! Yes, it is caused by some weird unicodes that hugging tokenizers cannot perfectly handle. Let me take a look and should be able to get back to you by the end of this week!

**Comment by lmessinger** [comment] 2022-11-07 13:04
Hi

any updates on this...? thanks!

**Comment by lolipopshock** [comment] 2022-11-14 04:30
OK this is fixed in #33

**Closed** 2022-11-14 04:30 UTC
